# site settings

title: Arthur G
description: Arthur G's personal page
taglong:
tagshort:
url: https://arthurka.eu
baseurl: ""
permalink: pretty
repo: https://github.com/arthurka-o/personal-website

# author settings

author:
  name: Arthur G.
  email: me@arthurka.eu
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: arthurka-o
  twitter: arthurka_eth

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
